import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { isAbsolute, resolve } from 'node:path';

// @lat: [[fork#The upstream guard]]
export const FORK_POINT = '65d2f5b220853b2b10dca3de18d511f575bc12c7';

// @lat: [[fork#The upstream guard#The allowlist]]
export const ALLOWLIST_FILE = 'fork-upstream-allowlist.tsv';

export const REASON_PLACEHOLDER = 'TODO';

const ALLOWLIST_HEADER = [
  '# Upstream files this fork is permitted to modify.',
  '#',
  '# Generated by `node dist/src/fork/upstream-guard-cli.js --regenerate`.',
  '# One entry per line: the repo-relative path, a TAB, then the reason the',
  '# fork must diverge in that file. A placeholder reason fails the check —',
  '# regenerate writes the marker, a person replaces it with the real reason.',
  '#',
  '# Deleting an upstream file is never allowlistable. See lat.md/fork.md.',
  '',
];

export type AllowEntry = {
  path: string;
  reason: string;
  line: number;
};

export type ParsedAllowlist = {
  entries: AllowEntry[];
  errors: string[];
};

export function parseAllowlist(text: string): ParsedAllowlist {
  const entries: AllowEntry[] = [];
  const errors: string[] = [];
  const seen = new Map<string, number>();

  text.split('\n').forEach((raw, index) => {
    const line = index + 1;
    const stripped = raw.replace(/\r$/, '');
    if (stripped.trim() === '' || stripped.trimStart().startsWith('#')) return;

    const tab = stripped.indexOf('\t');
    const split = tab >= 0 ? tab : stripped.search(/\s/);
    if (split < 0) {
      errors.push(
        `${ALLOWLIST_FILE}:${line}: entry has no reason: ${stripped}`,
      );
      return;
    }
    const path = stripped.slice(0, split).trim();
    const reason = stripped.slice(split + 1).trim();
    if (path === '') {
      errors.push(`${ALLOWLIST_FILE}:${line}: entry has no path`);
      return;
    }
    if (reason === '') {
      errors.push(`${ALLOWLIST_FILE}:${line}: entry has no reason: ${path}`);
      return;
    }
    const first = seen.get(path);
    if (first !== undefined) {
      errors.push(
        `${ALLOWLIST_FILE}:${line}: duplicate entry for ${path} ` +
          `(first at line ${first})`,
      );
      return;
    }
    seen.set(path, line);
    entries.push({ path, reason, line });
  });

  return { entries, errors };
}

export function renderAllowlist(entries: AllowEntry[]): string {
  const sorted = [...entries].sort((a, b) => (a.path < b.path ? -1 : 1));
  const body = sorted.map((e) => `${e.path}\t${e.reason}`);
  return [...ALLOWLIST_HEADER, ...body, ''].join('\n');
}

export function needsReason(reason: string): boolean {
  return reason.trimStart().toUpperCase().startsWith(REASON_PLACEHOLDER);
}

export type DiffEntry = {
  status: string;
  path: string;
};

export function parseNameStatus(raw: string): DiffEntry[] {
  const fields = raw.split('\0').filter((f) => f !== '');
  const out: DiffEntry[] = [];
  for (let i = 0; i + 1 < fields.length; i += 2) {
    out.push({ status: fields[i]!, path: fields[i + 1]! });
  }
  return out;
}

export type Finding = {
  kind: 'deletion' | 'unallowlisted' | 'missing-reason' | 'allowlist-error';
  path: string;
  message: string;
};

export type ClassifyInput = {
  diff: DiffEntry[];
  upstream: ReadonlySet<string>;
  allowlist: ReadonlyMap<string, string>;
};

export type ClassifyResult = {
  findings: Finding[];
  warnings: string[];
  touched: string[];
};

export function classify(input: ClassifyInput): ClassifyResult {
  const findings: Finding[] = [];
  const touched: string[] = [];

  for (const entry of input.diff) {
    if (!input.upstream.has(entry.path)) continue;
    touched.push(entry.path);

    if (entry.status.startsWith('D')) {
      findings.push({
        kind: 'deletion',
        path: entry.path,
        message:
          `${entry.path}: deletes an upstream file.\n` +
          '    No allowlist entry can permit this. A file this fork deletes ' +
          'conflicts on\n' +
          '    every future merge that touches it upstream; a file this fork ' +
          'modifies\n' +
          '    conflicts once and stays resolved. Leave the file in place and ' +
          'change\n' +
          '    what it does, or turn it off out of band.',
      });
      continue;
    }

    const reason = input.allowlist.get(entry.path);
    if (reason === undefined) {
      findings.push({
        kind: 'unallowlisted',
        path: entry.path,
        message:
          `${entry.path}: modifies an upstream file that is not allowlisted.\n` +
          '    Move the change into a new fork-owned file, or add the path to ' +
          `${ALLOWLIST_FILE}\n` +
          '    with the reason the fork must diverge here.',
      });
      continue;
    }
    if (needsReason(reason)) {
      findings.push({
        kind: 'missing-reason',
        path: entry.path,
        message:
          `${entry.path}: allowlisted with a placeholder reason.\n` +
          `    Replace the ${REASON_PLACEHOLDER} in ${ALLOWLIST_FILE} with why ` +
          'this file must diverge.',
      });
    }
  }

  const touchedSet = new Set(touched);
  const warnings: string[] = [];
  for (const path of input.allowlist.keys()) {
    if (!touchedSet.has(path)) {
      warnings.push(
        `${path}: allowlisted but no longer modified — regenerate to drop it.`,
      );
    }
  }

  return { findings, warnings, touched };
}

function git(repo: string, args: string[], stdin?: string) {
  const result = spawnSync('git', ['-C', repo, ...args], {
    input: stdin,
    encoding: 'utf-8',
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error) throw result.error;
  return result;
}

export function repoRoot(from: string): string {
  const result = git(from, ['rev-parse', '--show-toplevel']);
  if (result.status !== 0) {
    throw new Error(`not a git repository: ${from}`);
  }
  return result.stdout.trim();
}

export function hasCommit(repo: string, rev: string): boolean {
  return git(repo, ['cat-file', '-e', `${rev}^{commit}`]).status === 0;
}

export function diffAgainst(repo: string, rev: string): DiffEntry[] {
  const result = git(repo, [
    'diff',
    '--no-renames',
    '--name-status',
    '-z',
    rev,
    '--',
  ]);
  if (result.status !== 0) {
    throw new Error(`git diff against ${rev} failed: ${result.stderr.trim()}`);
  }
  return parseNameStatus(result.stdout);
}

export function upstreamPaths(
  repo: string,
  rev: string,
  paths: string[],
): Set<string> {
  const out = new Set<string>();
  if (paths.length === 0) return out;
  const batchable = paths.filter((p) => !p.includes('\n'));
  const input = batchable.map((p) => `${rev}:${p}`).join('\n') + '\n';
  const result = git(repo, ['cat-file', '--batch-check'], input);
  const lines = result.stdout.split('\n').filter((l) => l !== '');
  const aligned = lines.length === batchable.length;
  if (aligned) {
    lines.forEach((line, index) => {
      if (/ blob \d+$/.test(line)) out.add(batchable[index]!);
    });
  }
  const leftover = aligned ? paths.filter((p) => p.includes('\n')) : paths;
  for (const path of leftover) {
    const probe = git(repo, ['cat-file', '-t', `${rev}:${path}`]);
    if (probe.status === 0 && probe.stdout.trim() === 'blob') out.add(path);
  }
  return out;
}

export type GuardOptions = {
  repo: string;
  forkPoint: string;
  allowlistFile: string;
  regenerate: boolean;
  fetch: boolean;
};

// @lat: [[fork#The upstream guard#Running it in CI]]
export function fetchForkPoint(repo: string, rev: string): boolean {
  const result = git(repo, ['fetch', '--no-tags', '--depth=1', 'origin', rev]);
  return result.status === 0 && hasCommit(repo, rev);
}

export type GuardResult = {
  ok: boolean;
  report: string;
  findings: Finding[];
  warnings: string[];
};

function allowlistPathFor(options: GuardOptions): string {
  return isAbsolute(options.allowlistFile)
    ? options.allowlistFile
    : resolve(options.repo, options.allowlistFile);
}

function loadAllowlist(file: string): ParsedAllowlist {
  if (!existsSync(file)) return { entries: [], errors: [] };
  return parseAllowlist(readFileSync(file, 'utf-8'));
}

export function runGuard(options: GuardOptions): GuardResult {
  const root = repoRoot(options.repo);
  const opts = { ...options, repo: root };

  const present =
    hasCommit(root, opts.forkPoint) ||
    (opts.fetch && fetchForkPoint(root, opts.forkPoint));

  if (!present) {
    return {
      ok: false,
      report:
        `upstream-guard: fork point ${opts.forkPoint} is not in this ` +
        'repository.\n' +
        '    A shallow clone does not carry it. Fetch it first:\n' +
        `      git fetch --no-tags --depth=1 origin ${opts.forkPoint}\n`,
      findings: [],
      warnings: [],
    };
  }

  const file = allowlistPathFor(opts);
  const diff = diffAgainst(root, opts.forkPoint);
  const upstream = upstreamPaths(
    root,
    opts.forkPoint,
    diff.map((d) => d.path),
  );

  if (opts.regenerate) {
    return regenerateInto(file, diff, upstream);
  }

  const parsed = loadAllowlist(file);
  if (!existsSync(file)) {
    return {
      ok: false,
      report: `upstream-guard: allowlist not found at ${file}\n`,
      findings: [],
      warnings: [],
    };
  }

  const map = new Map(parsed.entries.map((e) => [e.path, e.reason]));
  const result = classify({ diff, upstream, allowlist: map });
  const findings = [
    ...parsed.errors.map(
      (message): Finding => ({ kind: 'allowlist-error', path: file, message }),
    ),
    ...result.findings,
  ];

  const lines: string[] = [];
  if (findings.length > 0) {
    lines.push(
      `upstream-guard: ${findings.length} violation(s) against fork point ` +
        `${opts.forkPoint.slice(0, 7)}`,
      '',
    );
    for (const finding of findings) lines.push(`  ${finding.message}`, '');
    lines.push(
      'The fork keeps its diff small: new behaviour goes in new fork-owned ' +
        'files,',
      'and an upstream file takes an import plus one call line. See ' +
        'lat.md/fork.md.',
    );
  } else {
    lines.push(
      `upstream-guard: ok — ${result.touched.length} upstream file(s) ` +
        'modified, all allowlisted.',
    );
  }
  for (const warning of result.warnings) lines.push(`  warning: ${warning}`);

  return {
    ok: findings.length === 0,
    report: lines.join('\n') + '\n',
    findings,
    warnings: result.warnings,
  };
}

function regenerateInto(
  file: string,
  diff: DiffEntry[],
  upstream: ReadonlySet<string>,
): GuardResult {
  const existing = new Map(
    loadAllowlist(file).entries.map((e) => [e.path, e.reason]),
  );
  const entries: AllowEntry[] = [];
  const deletions: Finding[] = [];
  const fresh: string[] = [];

  for (const entry of diff) {
    if (!upstream.has(entry.path)) continue;
    if (entry.status.startsWith('D')) {
      deletions.push({
        kind: 'deletion',
        path: entry.path,
        message:
          `${entry.path}: deletes an upstream file, which is never ` +
          'allowlistable — left out of the regenerated list.',
      });
      continue;
    }
    const reason =
      existing.get(entry.path) ??
      `${REASON_PLACEHOLDER}: why must this upstream file diverge?`;
    if (!existing.has(entry.path)) fresh.push(entry.path);
    entries.push({ path: entry.path, reason, line: 0 });
  }

  writeFileSync(file, renderAllowlist(entries), 'utf-8');

  const lines = [
    `upstream-guard: wrote ${entries.length} entr(ies) to ${file}`,
  ];
  for (const path of fresh) {
    lines.push(`  new entry needs a reason: ${path}`);
  }
  for (const finding of deletions) lines.push(`  ${finding.message}`);

  return {
    ok: deletions.length === 0,
    report: lines.join('\n') + '\n',
    findings: deletions,
    warnings: [],
  };
}

const USAGE = `Usage: node dist/src/fork/upstream-guard-cli.js [options]

  --regenerate          rewrite the allowlist from the current diff
  --fetch               fetch the fork point from origin if it is absent
  --fork-point <rev>    default ${FORK_POINT}
  --repo <dir>          default the current working directory
  --allowlist <file>    default <repo>/${ALLOWLIST_FILE}
  -h, --help            this text
`;

export function parseArgs(argv: string[]): GuardOptions | { help: true } {
  const options: GuardOptions = {
    repo: process.cwd(),
    forkPoint: FORK_POINT,
    allowlistFile: ALLOWLIST_FILE,
    regenerate: false,
    fetch: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]!;
    if (arg === '-h' || arg === '--help') return { help: true };
    else if (arg === '--regenerate' || arg === '--write')
      options.regenerate = true;
    else if (arg === '--fetch') options.fetch = true;
    else if (arg === '--fork-point') options.forkPoint = argv[++i] ?? '';
    else if (arg === '--repo') options.repo = argv[++i] ?? '';
    else if (arg === '--allowlist') options.allowlistFile = argv[++i] ?? '';
    else throw new Error(`unknown argument: ${arg}`);
  }
  return options;
}

export function main(argv: string[]): number {
  let options: GuardOptions | { help: true };
  try {
    options = parseArgs(argv);
  } catch (error) {
    process.stderr.write(`${(error as Error).message}\n\n${USAGE}`);
    return 2;
  }
  if ('help' in options) {
    process.stdout.write(USAGE);
    return 0;
  }
  let result: GuardResult;
  try {
    result = runGuard(options);
  } catch (error) {
    process.stderr.write(`upstream-guard: ${(error as Error).message}\n`);
    return 2;
  }
  process.stdout.write(result.report);
  return result.ok ? 0 : 1;
}
